apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170064665
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170064665
    app.kubernetes.io/part-of: test-app-170064665
  name: java-quarkus-170064665
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170064665
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170064665
    spec:
      containers:
      - image: quay.io/hacdev/st7e1vwu-tenant/test-app-170064665/java-quarkus-170064665@sha256:5529a472bdec160947c675ff6960880bb88324a277020c79787a2790e07f38df
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
