apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170064665
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/st7e1vwu-tenant/test-app-170064665/java-quarkus-170064665@sha256:5529a472bdec160947c675ff6960880bb88324a277020c79787a2790e07f38df
        name: my-java-quarkus
        resources: {}
status: {}
